name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Trigger website deploy
      run: |
        echo "Triggering deploy on www repo",
        curl -X POST -d {} https://api.netlify.com/build_hooks/5db5427494d914e3817eda8b
